### ISSUE TITLE
GwtOlDemoApplicationImpl

### ISSUE THREAD

**Issue by respeso** [TDesjardins/gwt-ol-demo#2]
I am trying to test the demo 'gwt-ol-demo', but I can not find the class 'GwtOlDemoApplicationImpl'. I could locate it in some way.

**Comment by FrankHossfeld** [comment]
This class will be generated once you have done a mvn clean install.

**Comment by TDesjardins** [comment]
@respeso Have you still problems to run the application with Maven?

**Comment by respeso** [comment]
I have not solved the problem yet. I'm testing with GWT material now. Without nalu.

**Comment by FrankHossfeld** [comment]
@respeso: the problem is, that the annotation processor of Nalu gets not triggered. It looks like your configuration is not correct, cause the problem works for me. 

Which IDE are you using?
What have you tried?

**Comment by respeso** [comment]
I'm using eclipse. And run As Maven build ... with goals gwt: devmode
This is the report:
[INFO] Scanning for projects...
[INFO] 
[INFO] ---------------< com.github.tdesjardins.ol:gwt-ol-demo >----------------
[INFO] Building GWT-OL-Demo with Domino-UI 1.1.0-SNAPSHOT
[INFO] ------------------------------[ gwt-app ]-------------------------------
[INFO] 
[INFO] >>> gwt-maven-plugin:1.0-rc-10:devmode (default-cli) > process-classes @ gwt-ol-demo >>>
[INFO] Downloading from : https://oss.sonatype.org/content/repositories/snapshots/com/github/nalukit/nalu/1.1.0-SNAPSHOT/maven-metadata.xml
[INFO] Downloaded from : https://oss.sonatype.org/content/repositories/snapshots/com/github/nalukit/nalu/1.1.0-SNAPSHOT/maven-metadata.xml (775 B at 634 B/s)
[INFO] Downloading from : https://oss.sonatype.org/content/repositories/snapshots/com/github/nalukit/nalu-parent/1.1.0-SNAPSHOT/maven-metadata.xml
[INFO] Downloaded from : https://oss.sonatype.org/content/repositories/snapshots/com/github/nalukit/nalu-parent/1.1.0-SNAPSHOT/maven-metadata.xml (608 B at 33 B/s)
[INFO] Downloading from : https://oss.sonatype.org/content/repositories/snapshots/com/github/nalukit/nalu-processor/1.1.0-SNAPSHOT/maven-metadata.xml
[INFO] Downloaded from : https://oss.sonatype.org/content/repositories/snapshots/com/github/nalukit/nalu-processor/1.1.0-SNAPSHOT/maven-metadata.xml (785 B at 1.4 kB/s)
[INFO] Downloading from : https://oss.sonatype.org/content/repositories/snapshots/com/github/nalukit/nalu-plugin-elemental2/1.1.0-SNAPSHOT/maven-metadata.xml
[INFO] Downloaded from : https://oss.sonatype.org/content/repositories/snapshots/com/github/nalukit/nalu-plugin-elemental2/1.1.0-SNAPSHOT/maven-metadata.xml (793 B at 2.0 kB/s)
[INFO] Downloading from : https://oss.sonatype.org/content/repositories/snapshots/com/github/nalukit/nalu-plugin-core-web/1.1.0-SNAPSHOT/maven-metadata.xml
[INFO] Downloaded from : https://oss.sonatype.org/content/repositories/snapshots/com/github/nalukit/nalu-plugin-core-web/1.1.0-SNAPSHOT/maven-metadata.xml (791 B at 2.2 kB/s)
[INFO] Downloading from : https://oss.sonatype.org/content/repositories/snapshots/org/dominokit/domino-ui/1.0-SNAPSHOT/maven-metadata.xml
[INFO] Downloaded from : https://oss.sonatype.org/content/repositories/snapshots/org/dominokit/domino-ui/1.0-SNAPSHOT/maven-metadata.xml (2.0 kB at 6.0 kB/s)
[INFO] Downloading from : https://oss.sonatype.org/content/repositories/snapshots/org/gwtproject/timer/gwt-timer/1.0-SNAPSHOT/maven-metadata.xml
[INFO] Downloading from : https://oss.sonatype.org/content/repositories/snapshots/org/gwtproject/safehtml/gwt-safehtml/1.0-SNAPSHOT/maven-metadata.xml
[INFO] Downloading from : https://oss.sonatype.org/content/repositories/snapshots/org/gwtproject/safehtml/safehtml-parent/1.0-SNAPSHOT/maven-metadata.xml
[INFO] Downloading from : https://oss.sonatype.org/content/repositories/snapshots/org/gwtproject/event/gwt-event/HEAD-SNAPSHOT/maven-metadata.xml
[INFO] Downloaded from : https://oss.sonatype.org/content/repositories/snapshots/org/gwtproject/event/gwt-event/HEAD-SNAPSHOT/maven-metadata.xml (1.2 kB at 3.3 kB/s)
[INFO] Downloading from : https://oss.sonatype.org/content/repositories/snapshots/org/gwtproject/i18n/gwt-cldr/1.0-SNAPSHOT/maven-metadata.xml
[INFO] Downloading from : https://oss.sonatype.org/content/repositories/snapshots/org/gwtproject/i18n/gwt-datetimeformat/1.0-SNAPSHOT/maven-metadata.xml
[INFO] Downloading from : https://oss.sonatype.org/content/repositories/snapshots/org/dominokit/domino-ui-ol-addon/1.0-SNAPSHOT/maven-metadata.xml
[INFO] Downloaded from : https://oss.sonatype.org/content/repositories/snapshots/org/dominokit/domino-ui-ol-addon/1.0-SNAPSHOT/maven-metadata.xml (1.2 kB at 3.5 kB/s)
[INFO] Downloading from : https://oss.sonatype.org/content/repositories/snapshots/org/dominokit/domino-ui-addons/1.0-SNAPSHOT/maven-metadata.xml
[INFO] Downloaded from : https://oss.sonatype.org/content/repositories/snapshots/org/dominokit/domino-ui-addons/1.0-SNAPSHOT/maven-metadata.xml (604 B at 1.8 kB/s)
[INFO] 
[INFO] --- gwt-maven-plugin:1.0-rc-10:enforce-encoding (default-enforce-encoding) @ gwt-ol-demo ---
[INFO] 
[INFO] --- gwt-maven-plugin:1.0-rc-10:add-super-sources (default-add-super-sources) @ gwt-ol-demo ---
[INFO] 
[INFO] --- gwt-maven-plugin:1.0-rc-10:add-test-super-sources (default-add-test-super-sources) @ gwt-ol-demo ---
[INFO] 
[INFO] --- build-helper-maven-plugin:3.0.0:add-source (add-source) @ gwt-ol-demo ---
[INFO] Source directory: C:\workspace_photon\gwt-ol-demo-master\target\generated-sources\annotations added.
[INFO] 
[INFO] --- gwt-maven-plugin:1.0-rc-10:generate-module (default-generate-module) @ gwt-ol-demo ---
[INFO] Overriding module short name demo with demo
[INFO] C:\workspace_photon\gwt-ol-demo-master\target\gwt-ol-demo-1.1.0-SNAPSHOT\WEB-INF\classes\com\github\tdesjardins\ol\demo\GwtOlDemo.gwt.xml up to date - skipping
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ gwt-ol-demo ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 28 resources
[INFO] skip non existing resourceDirectory C:\workspace_photon\gwt-ol-demo-master\src\main\super
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.1:compile (default-compile) @ gwt-ol-demo ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-war-plugin:3.0.0:exploded (copy-war-contents-to-exploded-dir) @ gwt-ol-demo ---
[INFO] Exploding webapp
[INFO] Assembling webapp [gwt-ol-demo] in [C:\workspace_photon\gwt-ol-demo-master\target\gwt-ol-demo-1.1.0-SNAPSHOT]
[INFO] Processing war project
[INFO] Copying webapp webResources [C:\workspace_photon\gwt-ol-demo-master\target/gwt-ol-demo-1.1.0-SNAPSHOT] to [C:\workspace_photon\gwt-ol-demo-master\target\gwt-ol-demo-1.1.0-SNAPSHOT]
[INFO] Copying webapp resources [C:\workspace_photon\gwt-ol-demo-master\src\main\webapp]
[INFO] Webapp assembled in [125 msecs]
[INFO] 
[INFO] <<< gwt-maven-plugin:1.0-rc-10:devmode (default-cli) < process-classes @ gwt-ol-demo <<<
[INFO] 
[INFO] 
[INFO] --- gwt-maven-plugin:1.0-rc-10:devmode (default-cli) @ gwt-ol-demo ---
[INFO] Error occurred during initialization of VM
[INFO] Could not reserve enough space for 2097152KB object heap
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 26.322 s
[INFO] Finished at: 2019-03-20T21:18:42+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.ltgt.gwt.maven:gwt-maven-plugin:1.0-rc-10:devmode (default-cli) on project gwt-ol-demo: GWT exited with status 1 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by FrankHossfeld** [comment]
Are you using Windows 7 with a 32-bit JVM?

**Comment by TDesjardins** [comment]
> [INFO] Error occurred during initialization of VM
[INFO] Could not reserve enough space for 2097152KB object heap

@respeso Seems this is a memory allocation problem. If you have a memory restriction you could try to decrease the memory in your pom: https://github.com/TDesjardins/gwt-ol-demo/blob/master/pom.xml#L168

**Comment by respeso** [comment]
Thank you very much for your help. The problem was in the use of a JRE instead of JDK. I do not know how I did not notice before.
Thanks again, and congratulations for your work.
